### ISSUE TITLE
Dom Exception

### ISSUE THREAD

**Issue by clonalejandro** [dominikhofacker/audiovisualization#1]
<h1>Error</h1>

• I downloaded your project when, I test your project, this give me this error:

<hr>
<img src="https://i.imgur.com/u7d30Mp.png">

**Comment by dominikhofacker** [comment]
Thanks for opening the issue. There has been an issue with the handleFiles() function but I have fixed it. Also, you can now play the attached sample file with a click of a button.
Additionally, the project is now working online and offline! 
(see [http://dominikhofacker.me/audiovisualization/](http://dominikhofacker.me/audiovisualization/))

There is still some work to do, that I might address in the near future like user feedback on file loading (as seen here: [http://dominikhofacker.me/Web-GL-Audio-Visualizer/](http://dominikhofacker.me/Web-GL-Audio-Visualizer/)), overall design and handling music files with no Tags or long song/album/artist names.
