### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by clonalejandro** [dominikhofacker/audiovisualization#2]
i would suggest, you create this project for Android in Java Lib, please, I love your project 😍

**Comment by dominikhofacker** [comment]
Thanks for the kind words. I am not planning to recreate this project in any way though, sorry about that. 

You can still view it on Android or any other device by opening the following website in your browser: 
[http://dominikhofacker.me/audiovisualization/](http://dominikhofacker.me/audiovisualization/)
