### ISSUE TITLE
Microphone input and Safari

### ISSUE THREAD

**Issue by eringee** [dominikhofacker/audiovisualization#7]
Hi there - I see that you mention that the mic input only works with FF and Chrome, do you know why this feature doesn't work with Safari?  Is it something that can be worked on or is it actually impossible at the moment?  I'd like to try to work on it just want more context

**Comment by dominikhofacker** [comment]
Hi there,

it seems to work for me as of right now meaning that this claim is outdated. 

Best,
Dominik
